name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: Restore dependencies
        run: dotnet restore --locked-mode
        
      - name: Build
        run: dotnet build --no-restore -c Release
        
      - name: Test
        run: dotnet test --no-build -c Release

      - name: Pack
        run: dotnet pack --no-build -c Release -o pack
