name: CI

on:
  push:
    branches: [ main, v*.* ]
  pull_request:
    branches: [ main, v*.* ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Push
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            3.1.x

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release

      - name: Pack
        run: dotnet pack --no-build -c Release -o pack

      - name: Push
        run: dotnet nuget push pack/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
